import os
from datetime import datetime
from fpdf import FPDF
import matplotlib.pyplot as plt
import numpy as np

class ForensicReportGenerator:
    def __init__(self, output_dir="results/reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)
        
    def generate_pdf(self, case_id, filename, prediction, confidence, risk_type, threat_level, trust_score, action, evidence_images=None):
        """
        Generates a professional PDF forensic report.
        evidence_images: list of paths to images (Grad-CAM heatmaps, etc.)
        """
        pdf = FPDF()
        pdf.add_page()
        
        # --- Header ---
        pdf.set_fill_color(11, 17, 33) # Dark Blue/Black from dashboard theme
        pdf.rect(0, 0, 210, 40, 'F')
        
        pdf.set_font('Helvetica', 'B', 24)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 20, "AI FORENSIC INCIDENT REPORT", 0, 1, 'C')
        
        pdf.set_font('Helvetica', '', 10)
        pdf.cell(0, 5, f"Enterprise Multimodal Synthetic Media Forensic Suite | Case ID: {case_id}", 0, 1, 'C')
        
        pdf.ln(20)
        
        # --- Metadata Section ---
        pdf.set_text_color(0, 0, 0)
        pdf.set_font('Helvetica', 'B', 14)
        pdf.cell(0, 10, "1. INCIDENT METADATA", 0, 1, 'L')
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)
        
        pdf.set_font('Helvetica', '', 11)
        data = [
            ["Case Identifier", case_id],
            ["Target Filename", filename],
            ["Analysis Timestamp", datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
            ["Detection Engine", "Forensic-CNN-LSTM v3.0 (Enterprise Analytics)"]
        ]
        
        for row in data:
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(50, 8, row[0], 0, 0)
            pdf.set_font('Helvetica', '', 10)
            pdf.cell(0, 8, f": {row[1]}", 0, 1)
            
        pdf.ln(10)
        
        # --- System Verdict ---
        pdf.set_font('Helvetica', 'B', 14)
        pdf.cell(0, 10, "2. SYSTEM VERDICT & RISK ASSESSMENT", 0, 1, 'L')
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)
        
        # Verdict Box
        verdict_color = (239, 68, 68) if prediction == "SYNTHETIC" else (34, 197, 94)
        pdf.set_fill_color(*verdict_color)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font('Helvetica', 'B', 16)
        pdf.cell(0, 15, f"VERDICT: {prediction} FORGERY DETECTED", 0, 1, 'C', True)
        
        pdf.ln(5)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font('Helvetica', '', 11)
        
        risk_data = [
            ["Trust Score", f"{trust_score:.2f} / 100"],
            ["Risk Level", threat_level],
            ["Classification", risk_type],
            ["Recommended Action", action]
        ]
        
        for row in risk_data:
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(50, 8, row[0], 0, 0)
            pdf.set_font('Helvetica', '', 10)
            pdf.cell(0, 8, f": {row[1]}", 0, 1)
            
        pdf.ln(10)
        
        # --- Forensic Evidence (Images) ---
        if evidence_images and len(evidence_images) > 0:
            pdf.set_font('Helvetica', 'B', 14)
            pdf.cell(0, 10, "3. MULTIMODAL FORENSIC EVIDENCE", 0, 1, 'L')
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(5)
            
            x_start = 10
            y_start = pdf.get_y()
            img_w = 90
            img_h = 90
            
            for i, img_path in enumerate(evidence_images[:2]): # Max 2 on first page
                if os.path.exists(img_path):
                    pdf.image(img_path, x=x_start + (i*95), y=y_start, w=img_w)
            
            pdf.set_y(y_start + img_h + 5)
            pdf.set_font('Helvetica', 'I', 9)
            pdf.cell(0, 10, "* Above images represent Spatial/Temporal artifacts localized by Grad-CAM tracing.", 0, 1, 'C')

        # --- Footer ---
        pdf.set_y(270)
        pdf.set_font('Helvetica', 'I', 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, "CONFIDENTIAL FORENSIC DOCUMENT - GENERATED BY TEAM 16 MAJOR PROJECT SUITE", 0, 0, 'C')
        
        report_filename = f"Forensic_Report_{case_id}.pdf"
        report_path = os.path.join(self.output_dir, report_filename)
        pdf.output(report_path)
        
        return report_path
